apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: demo
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: "7.3.7"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: demo
      interval: 1m
