---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kbot
  namespace: demo
spec:
  revisionHistoryLimit: 4
  chart:
    spec:
      chart: ./helm
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: kbot
  interval: 1m0s
  values:
    container:
      command: ["kbot"]
      args: ["start"]
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: kbot
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: METRICS_HOST
                  value: collector.demo.svc.cluster.local:4317
