apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: demo
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "5.37.4"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: demo
      interval: 1m
