apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: demo
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-operator
      version: "0.49.0"
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: demo
      interval: 1m
  values:
    admissionWebhooks:
      enabled: false
    certManager:
      enabled: false