apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: demo
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus
      version: "15.8.5"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: demo
      interval: 1m
