apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: demo
spec:
  interval: 5m
  chart:
    spec:
      chart: fluent-bit
      version: 0.49.1
      sourceRef:
        kind: HelmRepository
        name: fluent-bit
        namespace: demo
  values:
    serviceAccount:
      create: true
      name: fluent-bit

    daemonSet:
      enabled: true

    config:
      service: |
        [SERVICE]
          flush 1
          log_level error

      inputs: |
        [INPUT]
            Name              tail
            Tag               kube.*
            Path              /var/log/containers/*.log
            Parser            docker
            DB                /var/log/flb_kube.db
            Mem_Buf_Limit     50MB
            Skip_Long_Lines   On
            Refresh_Interval  10

      customParsers: |
        [PARSER]
            Name   docker
            Format json
            Time_Key time
            Time_Format %Y-%m-%dT%H:%M:%S.%L

      outputs: |
        [OUTPUT]
            Name opentelemetry
            Match *
            Host collector.demo.svc.cluster.local
            Metrics_uri          /v1/metrics
            Logs_uri             /v1/logs
            Traces_uri           /v1/traces
            Port 4318
            add_label app fluent-bit
            add_label color blue
      filters: |
        [FILTER]
            Name kubernetes
            Match kube.*
            Merge_Log On
            Keep_Log Off
            K8S-Logging.Parser On
            K8S-Logging.Exclude On
    