apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: demo
spec:
  interval: 5m
  chart:
    spec:
      chart: fluent-bit
      version: 0.49.1
      sourceRef:
        kind: HelmRepository
        name: fluent-bit
        namespace: demo
  values:
    outputs: |
      [OUTPUT]
          Name opentelemetry
          Match *
          Host collector.demo.svc.cluster.local
          Port 4317
          Mode grpc
