apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: demo
spec:
  interval: 5m
  releaseName: jaeger
  chart:
    spec:
      chart: jaeger
      version: "0.71.9"
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
  values:
    provisionDataStore:
      cassandra: false
      elasticsearch: false
      kafka: false
    allInOne:
      enabled: true
    collector:
      enabled: false
    agent:
      enabled: false
    query:
      enabled: false 