apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: demo
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 6.30.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: demo
  values:
    fullnameOverride: loki
    mode: "singleBinary"  # ← REQUIRED
    loki:
      memberlist:
        join_members: []
      results_cache:
        enabled: false
      ring:
        kvstore:
          store: inmemory
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      schemaConfig:
        configs:
          - from: "2022-01-01"
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi
        storageClassName: standard
    gateway:
      enabled: true
    serviceMonitor:
      enabled: true