apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: demo
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 6.30.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: demo
  values:
    fullnameOverride: loki

    deploymentMode: SingleBinary

    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        accessModes:
          - ReadWriteOnce
        size: 10Gi
        storageClassName: standard

    loki:
      auth_enabled: false
      server:
        http_listen_port: 3100
        grpc_listen_port: 9095

      common:
        instance_addr: 0.0.0.0
        ring:
          kvstore:
            store: inmemory

      limits_config:
        allow_structured_metadata: false
      ruler:
        alertmanager_url: http://prometheus-alertmanager.demo.svc.cluster.local:9093

      analytics:
        reporting_enabled: false
      storage:
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin

      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: loki_index_
              period: 24h

      storageConfig:
        boltdb_shipper:
          active_index_directory: /var/loki/index
          cache_location: /var/loki/cache
          shared_store: filesystem
        filesystem:
          directory: /var/loki/chunks

      ingester:
        chunk_encoding: snappy

      tracing:
        enabled: false  # Can enable if using OpenTelemetry

      querier:
        max_concurrent: 4

    # Optional: reduce other components to 0 for clarity
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
