apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: collector
  namespace: demo
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-collector
      version: 0.127.1
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: demo
  values:
    mode: deployment
    fullnameOverride: collector
    ports:
      metrics:
        enabled: true
    image:
      repository: otel/opentelemetry-collector-contrib
      tag: 0.128.0
    config:
      receivers:
        otlp:
          protocols:
            grpc: {}
            http: {}

      exporters:
        debug:
          verbosity: normal
        otlphttp/logs:
          endpoint: "http://loki-gateway.demo.svc.cluster.local/otlp"
          tls:
            insecure: true
        prometheus:
          endpoint: "0.0.0.0:8889"
        zipkin:
          endpoint: "http://jaeger-collector.demo.svc.cluster.local:9411/api/v2/spans"
      service:
        pipelines:
          logs:
            receivers: [otlp]
            exporters: [debug, otlphttp/logs]
          traces:
            receivers: [otlp]
            exporters: [debug, zipkin]
          metrics:
            receivers: [otlp]
            exporters: [debug, prometheus]