apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: collector
  namespace: demo
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-collector
      version: 0.127.1
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: demo
  values:
    mode: deployment
    fullnameOverride: collector
    image:
      repository: otel/opentelemetry-collector-contrib
      tag: 0.128.0
    config:
      receivers:
        otlp:
          protocols:
            grpc: {}
            http:
              endpoint: "0.0.0.0:3030"

      exporters:
        debug:
          verbosity: normal
        loki:
          endpoint: http://loki:3100/loki/otlp
            tls:
              insecure: true
        prometheus:
          endpoint: "0.0.0.0:8889"

      service:
        pipelines:
          logs:
            receivers: [otlp]
            exporters: [loki]
          traces:
            receivers: [otlp]
            exporters: [debug]
          metrics:
            receivers: [otlp]
            exporters: [debug, prometheus]
