apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: demo
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: demo
  values:
    fullnameOverride: prometheus
    serverFiles:
      prometheus.yml:
        global:
          scrape_interval: 15s
          evaluation_interval: 15s

        scrape_configs:
          - job_name: otel_collector
            scrape_interval: 5s
            static_configs:
              - targets: ['collector.demo.svc.cluster.local:8889']

          - job_name: prometheus
            static_configs:
              - targets: ['localhost:9090']
